### ISSUE TITLE
Check failed

### ISSUE THREAD

**Issue by whatsdis** [beniz/deepdetect#61] opened 2016-02-05 01:57 UTC
following this example

http://www.deepdetect.com/tutorials/imagenet-classifier/

I managed to create the service which outputs 

`{"status":{"code":201,"msg":"Created"}}`

but when I do 

`~/deepdetect/build/main# curl -X POST "http://localhost:8080/predict" -d "{\"service\":\"imageserv\",\"parameters\":{\"input\":{\"width\":224,\"height\":224},\"output\":{\"best\":3}},\"data\":[\"ambulance.jpg\"]}"
{"status":{"code":400,"msg":"BadRequest","dd_code":1005,"dd_msg":"Service Input Error"}}root@ubuntu-512mb-nyc2-01:~/deepdetect/build/main# curl -X POST "http://t:8080/predict" -d "{\"service\":\"imageserv\",\"parameters\":{\"input\":{\"width\":224,\"height\":224},\"output\":{\"best\":3}},\"data\":[\"../ambulance.jpg\"]}"`

yields the following message

`{"status":{"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"./include/caffe/syncedmem.hpp:26 / Check failed (custom): *ptr"}}`

also when I put the ambulance.jpg outside of deepdetect and run it from there I get 

`{"status":{"code":400,"msg":"BadRequest","dd_code":1005,"dd_msg":"Service Input Error"}}`

Please help!

**Comment by beniz** [comment] 2016-02-05 05:23
@whatsdis you do not have enough RAM to load the neural net. Googlenet will take around 1.5GB, make sure you have around 2GB available in RAM.

Duplicate of #46. Lack of memory on the GPU translates into #58.

**Closed** 2016-02-06 05:00 UTC
Labels: duplicate
