### ISSUE TITLE
Add support for the `Content-Encoding: gzip` content negotiation header

### ISSUE THREAD

**Issue by nrinaudo** [beniz/deepdetect#176] opened 2016-09-13 09:57 UTC
DeepDetect currently ignores the `Content-Encoding` header (used to transfer textual content, such as JSON, in a compressed form, typically gzip):

```
curl -v -XGET -H "Accept-Encoding: gzip" "http://localhost:8080/info"

> GET /info HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
> Accept-Encoding: gzip
> 
< HTTP/1.0 200 OK
< Content-Length: 160
< Content-Type: text/html
< 
{"status":{"code":200,"msg":"OK"},"head":{"method":"/info","version":"0.1","branch":"master","commit":"7a0b3b9684e8ad93e1bd18a9bf5fc024c5bc7dbf","services":[]}}
```

This is not a major issue, but gzipping response entities *has* brought measurable performance improvements in a production environment for similar services.

**Comment by beniz** [comment] 2016-09-13 14:04
Thanks. Let's limit this to `gzip` support which is a good thing to have when posting / getting large bodies.

**Comment by beniz** [comment] 2016-09-13 14:04
Useful C++ wrapper: http://www-d0.fnal.gov/d0dist/dist/packages/lm_access/devel/lm_access/gzstream.hpp

**Comment by beniz** [comment] 2016-09-14 17:19
@nrinaudo PR #180 fulfills first half of the requirement by compressing the response:

```
 curl --compressed -v -XGET -H "Accept-Encoding: gzip" "http://localhost:8080/info"
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /info HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> Accept-Encoding: gzip
> 
< HTTP/1.1 200 OK
< Content-Length: 156
< Content-Type: application/json
< Content-Encoding: gzip
< 
* Connection #0 to host localhost left intact
{"status":{"code":200,"msg":"OK"},"head":{"method":"/info","version":"0.1","branch":"gzip_176","commit":"3da10fb0ef6feb05562b7561f33afa491a6a4df5","services":[]}}
```

```
curl -v -XGET -H "Accept-Encoding: gzip" "http://localhost:8080/info"Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /info HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> Accept-Encoding: gzip
> 
< HTTP/1.1 200 OK
< Content-Length: 156
< Content-Type: application/json
< Content-Encoding: gzip
< 
* Connection #0 to host localhost left intact
��A�0E�2k�-���
                  `���3�E)�����;��{??����S`<��@0�J5��#<�p60����Y\���i+1/b�E
?                                                                              �
  N߸��`���R�⺀Z�SĖ�)cl�c5w2�7���F6��=z�O��y����}�
```

```
 curl -v -XGET "http://localhost:8080/info"
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /info HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 162
< Content-Type: application/json
< 
* Connection #0 to host localhost left intact
{"status":{"code":200,"msg":"OK"},"head":{"method":"/info","version":"0.1","branch":"gzip_176","commit":"3da10fb0ef6feb05562b7561f33afa491a6a4df5","services":[]}}
```

**Comment by beniz** [comment] 2016-09-14 17:20
Now, second part is compressed POST.
@nrinaudo can you confirm that adding up `Content-Encoding: gzip` to POST call should be enough to let the server know that posted content is compressed ?

**Comment by nrinaudo** [comment] 2016-09-14 17:29
Absolutely, although it might be a bit trickier than that: a lot of user agents will use chunked transfer encoding when submitting gzipped request entities. If not supported out of the box, it might be problematic to implement.

I'd vote for turning that into a separate issue - supporting gzipped responses is mandatory in the HTTP specs, but gzipped requests is more of a grey area.

**Comment by nrinaudo** [comment] 2016-09-14 17:31
Also, technically, deepdetect should support the deflate content encoding to be rfc compliant, but it's hardly ever encountered in the real world.

**Comment by beniz** [comment] 2016-09-14 17:39
we don't want to support complicated HTTP server stuff that can be done by putting an nginx in front. However I believe it makes sense to support compressed posted content in a single chunk. Useful when predicting over the network in CSV and SVM format. Since we support base64 for images, it could be useful there too. I'm looking for the minimum best / useful / simple elements to add here.

**Comment by beniz** [comment] 2016-09-15 17:24
Commit above updates PR #180 with support for POST with gzipped data.
@nrinaudo  It'd be useful if you have opportunity to give feedback on it, then it can be merged.

**Comment by nrinaudo** [comment] 2016-09-15 19:44
As far as I can tell, this works as expected. Thanks!

**Comment by beniz** [comment] 2016-09-16 05:48
Thanks. Merged.

**Closed by beniz** 2016-09-16 05:48 UTC
Labels: enhancement

**Comment by beniz** [comment] 2016-10-04 05:50
@nrinaudo hey, I'd be interested in your thoughts on #199 when you have a minute. I can reproduce from Chromium and FF.

**Comment by nrinaudo** [comment] 2016-10-04 08:03
You can actually reproduce it with curl as well: `curl -H "Accept-Encoding: gzip,deflate"`

Without looking at the code, it looks like DeepDetect will:
* declare a `Content-Encoding: gzip` header if it finds an `Accept-Encoding` one, regardless of its value.
* compress the data if and only if `Accept-Encoding` has a value of exactly `gzip`.

You can double-check that easily:

```
curl  http://127.0.0.1:8980/info -H "Accept-Encoding: deflate" -v
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8980 (#0)
> GET /info HTTP/1.1
> Host: 127.0.0.1:8980
> User-Agent: curl/7.43.0
> Accept: */*
> Accept-Encoding: deflate
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Length: 160
< Content-Type: application/json
< Content-Encoding: gzip
< 
* Closing connection 0
{"status":{"code":200,"msg":"OK"},"head":{"method":"/info","version":"0.1","branch":"master","commit":"6d0a1f2d1e487b492e004d7d5972f302d4182ab1","services":[]}}
```

Notice how the `Accept-Encoding` is set to `deflate`, the `Content-Encoding` to `gzip`, but the content is not actually encoded.

**Comment by beniz** [comment] 2016-10-04 08:05
thanks, it's been fixed earlier. I did update my initial message but die to GitHub outage this morning it appears to not have been updated.
